# version: '3.9'
# services:
#   blog-database:
#     image: mongo
#     ports:
#       - '27017:27017'
#   blog-backend:
#     build: backend/
#     environment:
#       - PORT=3001
#       - DATABASE_URL=mongodb://host.docker.internal:27017/blog
#     ports:
#       - '3001:3001'
#     depends_on:
#       - blog-database
#   blog-frontend:
#     build:
#       context: .
#       args:
#         VITE_BACKEND_URL: http://localhost:3001/api/v1
#     ports:
#       - '3000:80'
#     depends_on:
#       - blog-backend

# version: '3.9'
services:
  blog-database:
    image: mongo
    ports:
      - '27017:27017'
  blog-backend:
    build: backend/
    environment:
      - PORT=8080
      - DATABASE_URL=mongodb://blog-database:27017/blog
    ports:
      - '8080:8080'
    depends_on:
      - blog-database
  blog-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: http://localhost:8080/api/v1
    ports:
      - '3000:80'
    depends_on:
      - blog-backend
